environments:
  cicdus:
    pipelines:
      - cicdus_teamcity_ubuntu_agent_deploy
      - cicdus_teamcity_build_agent_deploy
      - cicdus_teamcity_cognos_agent_deploy
      - cicdus_teamcity_test_agent_deploy
