pipelines:
  "cicdus_teamcity_agent_deploy":
    environment_variables:
      AWS_CRED_DIR: /var/go/.aws/
      CHEF_CONFIG_DIR: ~/.chef/
      CHEF_SECRET_FILE: dev_encrypted_data_bag_secret
      DOCKER_IMAGE: daptiv/gocd-agent-ubuntu-16.04-terraform:0.10.8
      TF_ACTION: deploy
      TF_DESTROY_TARGETS: all
      TF_VARIABLE_FILE: us_cicd.tfvars
      TF_VARIABLE_PATH: ../../../terraform_environment/variables/
    secure_variables: # https://api.gocd.org/current/#encrypt-a-plain-text-value
      GO_AWS_ACCESS_KEY_ID: Xive1jvS6yEWkZxIbvfEM30k1WGKvTyK
      GO_AWS_SECRET_ACCESS_KEY: EiYBguOF/PHZC34qxczzGFTIhgdbpbK0CzbAEOh2ijx/cNwsvYJmhRPbjVrTlEdS
      SLACK_URL_SUFFIX: bGQzd0F8g7bN87sgMfGjcziigZLK0/DxLqBoVWRRFeFgqwDzZK9dcGaLMmMdjOh9
    group: teamcity
    label_template: "${COUNT}"
    locking: off
    materials:
      "teamcity":
        git: git@github.com:daptiv/teamcity.git
        branch: 187704_teamcity
        destination: teamcity
      "terraform_environment":
        git: git@github.com:daptiv/terraform_environment.git
        branch: 187704_teamcity
        destination: terraform_environment
    stages:
      - "Plan":
          clean_workspace: true
          jobs:
            "Execute":
              resources:
                - Docker
              tasks:
                - exec:
                    run_if: passed
                    command: /bin/bash
                    arguments:
                      - -c
                      - "docker pull $DOCKER_IMAGE"
                - exec:
                    run_if: passed
                    working_directory: teamcity/terraform/teamcity_agent
                    command: /bin/bash
                    arguments:
                      - -c
                      - "docker-compose run --rm terraform 'rake validate'"
                - exec:
                    run_if: passed
                    working_directory: teamcity/terraform/teamcity_agent
                    command: /bin/bash
                    arguments:
                      - -c
                      - "docker-compose run --rm terraform 'rake plan'"
      - "Deploy":
          approval: manual
          clean_workspace: true
          jobs:
            "Execute":
              resources:
                - Docker
              tasks:
                - exec:
                    run_if: passed
                    command: /bin/bash
                    arguments:
                      - -c
                      - "docker pull $DOCKER_IMAGE"
                - exec:
                    run_if: passed
                    working_directory: teamcity/terraform/teamcity_agent
                    command: /bin/bash
                    arguments:
                      - -c
                      - "docker-compose run --rm terraform 'rake notify[\"started\"]'"
                - exec:
                    run_if: passed
                    working_directory: teamcity/terraform/teamcity_agent
                    command: /bin/bash
                    arguments:
                      - -c
                      - "docker-compose run --rm terraform 'rake $TF_ACTION'"
                - exec:
                    run_if: failed
                    working_directory: teamcity/terraform/teamcity_agent
                    command: /bin/bash
                    arguments:
                      - -c
                      - "docker-compose run --rm terraform 'rake notify[\"failed\"]'"
      - "Verify":
          clean_workspace: true
          jobs:
            "Execute":
              resources:
                - Docker
              tasks:
                - exec:
                    run_if: passed
                    command: /bin/bash
                    arguments:
                      - -c
                      - "docker pull $DOCKER_IMAGE"
                - exec:
                    run_if: passed
                    working_directory: teamcity/terraform/teamcity_agent
                    command: /bin/bash
                    arguments:
                      - -c
                      - "docker-compose run --rm terraform 'rake verify'"
                - exec:
                    run_if: passed
                    working_directory: teamcity/terraform/teamcity_agent
                    command: /bin/bash
                    arguments:
                      - -c
                      - "docker-compose run --rm terraform 'rake notify[\"passed\"]'"
                - exec:
                    run_if: failed
                    working_directory: teamcity/terraform/teamcity_agent
                    command: /bin/bash
                    arguments:
                      - -c
                      - "docker-compose run --rm terraform 'rake notify[\"failed\"]'"
