# How to use this file:
# docker-compose run --rm terraform rake deploy

version: '2'
services:
  terraform:
    image: ${DOCKER_IMAGE}
    volumes:
      - $PWD:/src/
      - ${AWS_CRED_DIR}:/root/.aws/
      - ${CHEF_CONFIG_DIR}:/root/.chef/
      - ${TF_VARIABLE_PATH}:/terraform_environment/variables/
      - ~/.ssh:/root/.ssh/
    working_dir: /src/
    network_mode: "host"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      CHEF_SECRET_FILE: /root/.chef/${CHEF_SECRET_FILE}
      GO_AWS_ACCESS_KEY_ID: ${GO_AWS_ACCESS_KEY_ID}
      GO_AWS_SECRET_ACCESS_KEY: ${GO_AWS_SECRET_ACCESS_KEY}
      GO_JOB_NAME: ${GO_JOB_NAME}
      GO_PIPELINE_COUNTER: ${GO_PIPELINE_COUNTER}
      GO_PIPELINE_NAME: ${GO_PIPELINE_NAME}
      GO_SERVER_URL: http://gocd.daptiv.com:8153
      GO_STAGE_COUNTER: ${GO_STAGE_COUNTER}
      GO_STAGE_NAME: ${GO_STAGE_NAME}
      SERVICE_NAME: ${SERVICE_NAME}
      SLACK_URL_SUFFIX: ${SLACK_URL_SUFFIX}
      TF_ACTION: ${TF_ACTION}
      TF_DESTROY_TARGETS: ${TF_DESTROY_TARGETS}
      TF_VARIABLE_FILE: ${TF_VARIABLE_FILE}
      TF_VARIABLE_PATH: /terraform_environment/variables
    command: |
      bash -c 'bash -s <<EOF
      echo "Please enter the command to execute:"
      echo "Ex: docker-compose run --rm terraform rake deploy"
      EOF'
