---
driver:
  name: ec2
  require_chef_omnibus: <%= ENV['REQUIRE_CHEF_OMNIBUS'] %>
  tags: {
    "Name": <%= ENV['COOKBOOK'] %>
  }
  aws_ssh_key_id: <%= ENV['EC2_SSH_KEY_ID'] %>
  instance_type: <%= ENV['EC2_INSTANCE_TYPE'] %>
  region: <%= ENV['EC2_REGION'] %>
  availability_zone: <%= ENV['EC2_AZ'] %>
  subnet_id: <%= ENV['EC2_SUBNET_ID'] %>
  security_group_ids: [<%= ENV['EC2_SG'] %>]
  retryable_tries: 240

provisioner:
  name: chef_zero
  environments_path: test/environments
  client_rb:
    environment: cookbook_ci

platforms:
  - name: ubuntu
    driver:
      image_search:
        "name": <%= ENV['EC2_UBUNTU_IMAGE_NAME'] %>
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            delete_on_termination: true
    transport:
      name: ssh
      username: <%= ENV['SSH_USER'] %>
      ssh_key: <%= ENV['SSH_KEY'] %>
  - name: windows
    transport:
      name: winrm
      username: <%= ENV['WIN_USER'] %>
      password: <%= ENV['WIN_PASS'] %>
    driver:
      image_search:
        "name": <%= ENV['EC2_IMAGE_NAME'] %>

suites:
  - name: <%= ENV['COOKBOOK'] %>
    includes: windows
    data_bags_path: <%= ENV['CHEF_DATA_BAGS'] %>
    encrypted_data_bag_secret_key_path: <%= ENV['CHEF_SECRET_FILE'] %>
    run_list:
      # - recipe[daptiv_buildagent_ppm_role::default]
      - recipe[daptiv_teamcity]
      - recipe[minitest-handler]
    attributes:
      daptiv_site:
        version: <%= ENV['LATEST_PPM_PACKAGE'] %>
  - name: <%= ENV['COOKBOOK'] %>
    includes: ubuntu
    data_bags_path: <%= ENV['CHEF_DATA_BAGS'] %>
    encrypted_data_bag_secret_key_path: <%= ENV['CHEF_SECRET_FILE'] %>
    run_list:
      - recipe[daptiv_buildagent_ubuntu_role]
      - recipe[daptiv_teamcity]
